version: '3.8'

services:
    # Servicio PHP/Laravel (basado en Sail)
    laravel.test:  
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                MYSQL_CLIENT: mariadb-client
        image: 'sail-8.4/app'
        container_name: laravel_test
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            DB_HOST: 'mariadb'
            DB_PORT: '3306'
            DB_DATABASE: '${DB_DATABASE}'
            DB_USERNAME: '${DB_USERNAME}'
            DB_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - bodega_integrada
        depends_on:
            - mariadb
        restart: unless-stopped
        expose:
            - '9000'

    # Servicio Nginx
    nginx:
        image: nginx:alpine
        container_name: nginx_server
        ports:
            - '${APP_PORT:-8080}:80'
        volumes:
            - '.:/var/www/html'
            - './docker/config/nginx/site.conf:/etc/nginx/conf.d/default.conf'
            - './docker/logs/nginx:/var/log/nginx'
        depends_on:
            - laravel.test 
        networks:
            - bodega_integrada
        restart: unless-stopped

    # Servicio MariaDB
    mariadb:
        image: 'mariadb:11'
        container_name: mariadb_db
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - bodega_integrada
        healthcheck:
            test:
                - CMD
                - healthcheck.sh
                - '--connect'
                - '--innodb_initialized'
            retries: 3
            timeout: 5s
        restart: unless-stopped

networks:
    bodega_integrada:
        driver: bridge

volumes:
    sail-mariadb:
        driver: local